config/routes.rb
Rails.application.routes.draw do

  resources :todos
  root 'todos#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo
    else
      render 'new'
    end
  end

  private

    def todo_params
      params.require(:todo).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/todos/index.html.erb
<h1>Todo App</h1>

<%= link_to "New Todo", new_todo_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

  <% @todos.each do |todo| %>
    <tr>
      <td><%= todo.title %></td>
      <td><%= todo.description %></td>
      <td><%= link_to "Show", todo_path(todo) %></td>
    </tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<h1>Create New Todo</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<p>
  <strong>Title:</strong><br>
  <%= @todo.title %>
</p>
<p>
  <strong>Description:</strong><br>
  <%= @todo.description %>
</p>

<%= link_to "Back", todos_path %>